paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: Cathy's Blog
description: 
author:
  name: Cathy
  email: cathy.xuejiao@gmail.com
  github: xuewu

categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://xuewu.github.io/cathy.github.io